version: '3.8'

services:
  mongo:
    image: mongo:8.0
    container_name: my_mongo
    ports:
      - "28017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  core-api:
    build: ./backend
    container_name: my_core_api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    environment:
      MONGODB_CONNECTION_URL: ${MONGODB_CONNECTION_URL}

  web:
    build: ./web
    container_name: my_web_server
    ports:
      - "5000:5000"
    depends_on:
      - core-api
    env_file:
      - ./web/.env
    environment:
      CORE_API_URL: http://core-api:8000

volumes:
  mongo_data: