version: '3.8'

services:
  mongo:
    image: mongo:8.0
    container_name: my_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  core-api:
    build: ./backend
    container_name: my_core_api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    environment:
      MONGODB_CONNECTION_URL: mongodb://mongo:27017 

  web:
    build: ./web
    container_name: my_web_server
    ports:
      - "5000:5000"
    depends_on:
      - core-api
    env_file:
      - ./web/.env
    environment:
      CORE_API_URL: http://core-api:8000

volumes:
  mongo_data: